export const complaints = [
  { id: "102", value: "Aura" },
  { id: "103", value: "Anorexia" },
  { id: "105", value: "Anxiety" },
  { id: "106", value: "Anxious" },
  { id: "109", value: "Acute onset" },
  { id: "11", value: "Aggravated by movement" },
  { id: "110", value: "Anxiety" },
  { id: "111", value: "Amenorrhea" },
  { id: "135", value: "Arthralgia" },
  { id: "138", value: "Apathetic" },
  { id: "14", value: "Arthralgia" },
  { id: "140", value: "Abdominal pain" },
  { id: "141", value: "Abdominal pain" },
  { id: "143", value: "Abdominal Pain" },
  { id: "18", value: "Arthralgia" },
  { id: "2", value: "Abdominal pain" },
  { id: "2", value: "Alteration of defecation pattern" },
  { id: "27", value: "Abdominal pain" },
  { id: "28", value: "Arthralgia" },
  { id: "30", value: "Anxious" },
  { id: "31", value: "Abdominal pain" },
  { id: "31", value: "Abdominal cramp" },
  { id: "35", value: "Anxiety" },
  { id: "36", value: "Aggravated by laying position" },
  { id: "42", value: "Abdominal cramp" },
  { id: "42", value: "Abdominal pain" },
  { id: "42", value: "Acute diarrhea" },
  { id: "5", value: "Alleviate by resting" },
  { id: "5", value: "Aggravate by doing activity" },
  { id: "6", value: "Anxiety" },
  { id: "72", value: "Abdominal pain" },
  { id: "96", value: "Anxiety" },
  { id: "97", value: "Aphasia" },
  { id: "97", value: "Ataxia " },
  { id: "98", value: "Aura" },
  { id: "98", value: "Altered Consciousness" },
  { id: "1", value: "Black colored stool" },
  { id: "1", value: "Black colored vomiting" },
  { id: "106", value: "Bizare behavior" },
  { id: "107", value: "Bad sleep quality" },
  { id: "11", value: "Bilateral joint pain" },
  { id: "110", value: "Burn sensation on the wound" },
  { id: "112", value: "Blurred vision" },
  { id: "113", value: "Blurred vision" },
  { id: "116", value: "Bleeding after labor" },
  { id: "117", value: "Begin with membranes rupture" },
  { id: "120", value: "Breast pain" },
  { id: "129", value: "Blood coming out from the nose" },
  { id: "133", value: "Boils inside the nose" },
  { id: "21", value: "Bloody stool" },
  { id: "24", value: "Bloating" },
  { id: "24", value: "Bloody stool" },
  { id: "26", value: "Bloody cough" },
  { id: "30", value: "Blurred vision" },
  { id: "31", value: "Bloating" },
  { id: "36", value: "Burning sensation inside the chest" },
  { id: "37", value: "Blurry-starry vision" },
  { id: "42", value: "Bloating" },
  { id: "44", value: "Bullae" },
  { id: "45", value: "Blood driping from anus" },
  { id: "50", value: "Borderline red spot" },
  { id: "56", value: "Burning sensation" },
  { id: "64", value: "Burning sensation" },
  { id: "67", value: "Burning sensation" },
  { id: "72", value: "Burning sensation" },
  { id: "72", value: "Bumps" },
  { id: "73", value: "Burning sensation" },
  { id: "78", value: "Burning sensation on genital" },
  { id: "80", value: "Bleeding between menstruation" },
  { id: "82", value: "Blurred vision" },
  { id: "83", value: "Blurred vision" },
  { id: "84", value: "Blurred vision" },
  { id: "85", value: "Blurred vision on far objects" },
  { id: "89", value: "Burning sensation" },
  { id: "90", value: "Burning sensation on eyelid" },
  { id: "103", value: "Constipation" },
  { id: "11", value: "Chronic fatigue" },
  { id: "116", value: "Cold Sweat" },
  { id: "117", value: "Cramp pelvic pain" },
  { id: "12", value: "Crepitation" },
  { id: "125", value: "Cough" },
  { id: "13", value: "Chest pain" },
  { id: "13", value: "Chronic Cough" },
  { id: "131", value: "Cough" },
  { id: "135", value: "Coughing" },
  { id: "136", value: "Cough" },
  { id: "137", value: "Chronic Cough" },
  { id: "138", value: "Cranky/Fussy" },
  { id: "14", value: "Chill" },
  { id: "140", value: "Constipation" },
  { id: "140", value: "Cough" },
  { id: "142", value: "Constipation" },
  { id: "144", value: "Coughing" },
  { id: "15", value: "Cough" },
  { id: "19", value: "Cough" },
  { id: "19", value: "Constipation" },
  { id: "20", value: "Chronic Cough" },
  { id: "22", value: "Chill" },
  { id: "26", value: "Chest pain" },
  { id: "26", value: "Chill" },
  { id: "27", value: "Calf tenderness" },
  { id: "27", value: "Chill" },
  { id: "3", value: "Constant severe abdominal pain" },
  { id: "30", value: "Chest pain" },
  { id: "32", value: "Chronic diarrhea" },
  { id: "34", value: "Chill" },
  { id: "35", value: "Coma" },
  { id: "35", value: "Cold sweating" },
  { id: "37", value: "Chest pain" },
  { id: "43", value: "Cranky" },
  { id: "5", value: "Cold sweating" },
  { id: "5", value: "Chest pain" },
  { id: "6", value: "Cold sweating" },
  { id: "6", value: "Chest pain" },
  { id: "7", value: "Chest pain" },
  { id: "79", value: "Chest pain" },
  { id: "9", value: "Chest pain" },
  { id: "96", value: "Cranial nerve disturbance" },
  { id: "98", value: "Confusion after seizure" },
  { id: "100", value: "Decreased sense of taste on the tongue" },
  { id: "100", value: "Dry eye" },
  { id: "101", value: "Difficulty to learn new information" },
  { id: "103", value: "Diffuse headache" },
  { id: "105", value: "Diarrhea" },
  { id: "106", value: "Delusion" },
  { id: "109", value: "Diminished attention" },
  { id: "116", value: "Dizziness" },
  { id: "14", value: "Diarrhea" },
  { id: "140", value: "Diarrhea" },
  { id: "140", value: "Distended abdomen" },
  { id: "141", value: "Dysuria" },
  { id: "142", value: "Diarrhea" },
  { id: "143", value: "Diarrhea" },
  { id: "16", value: "Diarrhea" },
  { id: "17", value: "Disoriented" },
  { id: "19", value: "Dizziness" },
  { id: "19", value: "Diarrhea" },
  { id: "2", value: "Dripping blood form anus on defecation" },
  { id: "20", value: "Dyspnea at night" },
  { id: "20", value: "Dyspnea at morning" },
  { id: "22", value: "Dysuria terminal" },
  { id: "24", value: "Diarrhea" },
  { id: "27", value: "Diarrhea" },
  { id: "28", value: "Dark-colored urine" },
  { id: "29", value: "Dark colored urine" },
  { id: "30", value: "Dizziness" },
  { id: "31", value: "Diarrhea" },
  { id: "35", value: "Decrease in consciousness" },
  { id: "35", value: "Dizziness" },
  { id: "37", value: "Dizziness" },
  { id: "37", value: "Decrease concentration" },
  { id: "38", value: "Decrease body weight of unknown reason" },
  { id: "45", value: "Dizziness" },
  { id: "47", value: "Difficulty to move on the site of trauma" },
  { id: "47", value: "Deformity on the site of trauma" },
  { id: "48", value: "Deformity on the site of trauma" },
  { id: "48", value: "Difficulty to move on the site of trauma" },
  { id: "49", value: "Diarrhea" },
  { id: "49", value: "Dysuria" },
  { id: "52", value: "Distended abdomen" },
  { id: "52", value: "Diarrhea" },
  { id: "59", value: "Dizziness" },
  { id: "62", value: "Dandruff on head skin" },
  { id: "7", value: "Dizziness" },
  { id: "71", value: "Discomfort" },
  { id: "74", value: "Decrease sense of taste" },
  { id: "77", value: "Dysuria" },
  { id: "8", value: "Dyspnea on exertion" },
  { id: "80", value: "Dysuria" },
  { id: "81", value: "Dysuria" },
  { id: "81", value: "Dysuria" },
  { id: "85", value: "Dizziness" },
  { id: "86", value: "Dazzled" },
  { id: "93", value: "Difficult to adapt in darkness" },
  { id: "95", value: "Diarrhea" },
  { id: "95", value: "Dry skin" },
  { id: "96", value: "Dysphagia" },
  { id: "97", value: "Dysphagia" },
  { id: "97", value: "Double vision" },
  { id: "101", value: "Easily forget" },
  { id: "105", value: "Easily tired" },
  { id: "105", value: "Epigastric pain" },
  { id: "109", value: "Emotion disorder" },
  { id: "110", value: "Excessive salivation" },
  { id: "110", value: "Excessive sweating" },
  { id: "110", value: "Excessive tears" },
  { id: "111", value: "Epigastric pain" },
  { id: "112", value: "Epigastric pain" },
  { id: "112", value: "Edema" },
  { id: "113", value: "Epigastric pain" },
  { id: "117", value: "Expulsion of fetal tissue" },
  { id: "118", value: "Enlargement of breast" },
  { id: "119", value: "Easily get tired" },
  { id: "127", value: "Ear tenderness" },
  { id: "127", value: "Ear pain" },
  { id: "128", value: "Ear pain" },
  { id: "130", value: "Ear pain" },
  { id: "136", value: "Exhaustion after cough" },
  { id: "138", value: "Edema" },
  { id: "142", value: "Epigastric pain" },
  { id: "16", value: "Excessive sweat" },
  { id: "18", value: "Epistaxis" },
  { id: "18", value: "Epigastric pain" },
  { id: "19", value: "Evening & Night Fever" },
  { id: "23", value: "Epigastric pain" },
  { id: "38", value: "Erectile dysfunction in men" },
  { id: "44", value: "Erythema" },
  { id: "51", value: "Extremities & scrotum enlargement" },
  { id: "7", value: "Easily exhausted" },
  { id: "79", value: "Enlargement of lymph node" },
  { id: "85", value: "Eyes easily get tired" },
  { id: "92", value: "Eyelashes loss" },
  {
    id: "99",
    value: "Ever get antiepileptic drugs and sudden drug withdrawal",
  },
  { id: "107", value: "Fatigue" },
  { id: "107", value: "Frequently wake up at night" },
  { id: "109", value: "Fluctuation" },
  { id: "110", value: "Fever" },
  { id: "110", value: "Fatique" },
  { id: "111", value: "Fatigue" },
  { id: "117", value: "Fever" },
  { id: "119", value: "Fatique" },
  { id: "120", value: "Fever" },
  { id: "122", value: "Fever" },
  { id: "123", value: "Fever" },
  { id: "127", value: "Fever" },
  { id: "128", value: "Fever" },
  { id: "128", value: "Full sense of the ear" },
  { id: "13", value: "Fatique" },
  { id: "130", value: "Full sense of the ear" },
  { id: "131", value: "Fever" },
  { id: "132", value: "Fever" },
  { id: "132", value: "Fatigue" },
  { id: "135", value: "Fever" },
  { id: "137", value: "Fever" },
  { id: "138", value: "Fussy child/cranky" },
  { id: "139", value: "Fatigue" },
  { id: "14", value: "Fever" },
  { id: "141", value: "Fever" },
  { id: "144", value: "Fatigue" },
  { id: "144", value: "Fever" },
  { id: "145", value: "Fatigue" },
  { id: "145", value: "Fever" },
  { id: "15", value: "Fever" },
  { id: "16", value: "Fatigue" },
  { id: "18", value: "Fever" },
  { id: "2", value: "Fever" },
  { id: "22", value: "Fever" },
  { id: "24", value: "Fever" },
  { id: "25", value: "Fever" },
  { id: "26", value: "Fever" },
  { id: "27", value: "Fever" },
  { id: "28", value: "Fever" },
  { id: "28", value: "Fatigue" },
  { id: "29", value: "Fatigue" },
  { id: "3", value: "Fever" },
  { id: "3", value: "Fatigue" },
  { id: "34", value: "Fever" },
  { id: "37", value: "Fatigue" },
  { id: "4", value: "Flatulence" },
  { id: "4", value: "Fever" },
  { id: "43", value: "Fever" },
  { id: "45", value: "Fatigue" },
  { id: "49", value: "Fever" },
  { id: "5", value: "Felt like pressed by heavy object" },
  { id: "51", value: "Fever" },
  { id: "58", value: "Fatigue" },
  { id: "58", value: "Fever" },
  { id: "59", value: "Fatique" },
  { id: "59", value: "Fever" },
  { id: "6", value: "Felt like pressed by heavy object" },
  { id: "65", value: "Fatique" },
  { id: "78", value: "Fluor albus" },
  { id: "79", value: "Fatique" },
  { id: "79", value: "Fever" },
  { id: "81", value: "Fever" },
  { id: "81", value: "Fatique" },
  { id: "86", value: "Foggy vision" },
  { id: "9", value: "Fatigue" },
  { id: "95", value: "Fever" },
  { id: "18", value: "Gum bleeding" },
  { id: "79", value: "Guma" },
  { id: "88", value: "Gritty" },
  { id: "91", value: "Gritty on the eyelid" },
  { id: "1", value: "History of previous vomiting" },
  { id: "10", value: "Hip pain" },
  { id: "10", value: "Hip stiffness" },
  { id: "103", value: "Heavy" },
  { id: "105", value: "Headache" },
  { id: "106", value: "Hallucination" },
  { id: "107", value: "Hard to sleep" },
  { id: "108", value: "High Fever" },
  { id: "110", value: "Hydrophobia" },
  { id: "123", value: "Halitosis" },
  { id: "123", value: "Headache" },
  { id: "128", value: "Hearing loss" },
  { id: "13", value: "Hemoptysis" },
  { id: "131", value: "Hoarse Voice" },
  { id: "134", value: "Hiposmia to Anosmia" },
  { id: "135", value: "Headache" },
  { id: "14", value: "Headache" },
  { id: "141", value: "Hematuria" },
  { id: "141", value: "Headache" },
  { id: "143", value: "Headache" },
  { id: "145", value: "Headache" },
  { id: "16", value: "Hot intolerance" },
  { id: "16", value: "Hair loss" },
  { id: "17", value: "Hemiparesis" },
  { id: "18", value: "Hemiparesis" },
  { id: "18", value: "Headache" },
  { id: "19", value: "Headache" },
  { id: "2", value: "Hematochezia" },
  { id: "20", value: "Heavy chest" },
  { id: "21", value: "Headache" },
  { id: "22", value: "High Fever" },
  { id: "27", value: "Headache" },
  { id: "30", value: "Headache" },
  { id: "35", value: "Hunger" },
  { id: "37", value: "Headache" },
  { id: "44", value: "Hot skin" },
  { id: "58", value: "Headache" },
  { id: "72", value: "Headache" },
  { id: "81", value: "Hot sensation" },
  { id: "81", value: "Hematuria" },
  { id: "83", value: "Headache" },
  { id: "99", value: "History of epilepsy" },
  { id: "103", value: "Insomnia" },
  { id: "103", value: "Intermittent " },
  { id: "106", value: "Inability to take care of self" },
  { id: "106", value: "Irritable" },
  { id: "124", value: "Itchy eyes" },
  { id: "125", value: "Itchy nose" },
  { id: "141", value: "Itching" },
  { id: "142", value: "Itching on skin" },
  { id: "145", value: "Itching" },
  { id: "16", value: "Increased appetite" },
  { id: "16", value: "Insomnia" },
  { id: "16", value: "Irritability" },
  { id: "19", value: "Insomnia" },
  { id: "38", value: "Itching" },
  { id: "40", value: "Itching" },
  { id: "45", value: "Iritated perianal skin" },
  { id: "50", value: "Itching" },
  { id: "52", value: "Itching" },
  { id: "53", value: "Itching especially at night or free time" },
  { id: "54", value: "Itching" },
  { id: "55", value: "Intermittent" },
  { id: "55", value: "Itching" },
  { id: "56", value: "Itching" },
  { id: "57", value: "Itching" },
  { id: "57", value: "Itching more severe at night" },
  { id: "58", value: "Inflammation skin of penis in male" },
  { id: "59", value: "Itching" },
  { id: "60", value: "Itching" },
  { id: "62", value: "Itching" },
  { id: "63", value: "Itching" },
  { id: "64", value: "Itching" },
  { id: "65", value: "Itching" },
  { id: "66", value: "Itching" },
  { id: "67", value: "Itching" },
  { id: "68", value: "Itching on the head" },
  { id: "69", value: "Itching when sweating" },
  { id: "70", value: "Itching" },
  { id: "71", value: "Itching" },
  { id: "72", value: "Itching" },
  { id: "73", value: "Itching" },
  { id: "74", value: "Itching on mouth" },
  { id: "76", value: "Itching when sweating" },
  { id: "77", value: "Itching on genital" },
  { id: "78", value: "Irritation on genital" },
  { id: "78", value: "Itching on genital" },
  { id: "80", value: "Itching" },
  { id: "81", value: "Itching" },
  { id: "88", value: "Itchy eyes" },
  { id: "89", value: "Itching on eye" },
  { id: "92", value: "Itching on the eyelid" },
  { id: "96", value: "Irritable" },
  { id: "11", value: "Joint swelling" },
  { id: "12", value: "Joint pain" },
  { id: "27", value: "Jaundice" },
  { id: "28", value: "Jaundice" },
  { id: "29", value: "Jaundice" },
  { id: "34", value: "Joint edema" },
  { id: "105", value: "Loss of interest" },
  { id: "11", value: "Loss of appetite" },
  { id: "111", value: "Loss of apetite" },
  { id: "114", value: "Leakage of fluid out of vagina" },
  { id: "122", value: "Loss of appetite" },
  { id: "123", value: "Lethargy" },
  { id: "123", value: "Loss of appetite" },
  { id: "128", value: "Loss of appetite" },
  { id: "13", value: "Loss of appetite" },
  { id: "132", value: "Loss of appetite" },
  { id: "132", value: "Lump on cheek in front of ear" },
  { id: "136", value: "Loss of appetite" },
  { id: "138", value: "Look wistful" },
  { id: "14", value: "Loss of appetite" },
  { id: "140", value: "Loss of appetite" },
  { id: "141", value: "Leg pain" },
  { id: "143", value: "Loss of apetite" },
  { id: "16", value: "Lump in front of the neck" },
  { id: "19", value: "Loss of appetite" },
  { id: "21", value: "Left lower quadrant abdominal pain" },
  { id: "23", value: "Loss of appetite" },
  { id: "27", value: "Loss of appetite" },
  { id: "28", value: "Loss of appetite" },
  { id: "37", value: "Loss of appetite" },
  { id: "45", value: "Lump on anus" },
  { id: "46", value: "Lump grows slowly" },
  { id: "49", value: "Loss of appetite" },
  { id: "7", value: "Loss of consciousness" },
  { id: "75", value: "Loss of sensation" },
  { id: "81", value: "Lower abdominal pain" },
  { id: "97", value: "Loss of consciousness " },
  { id: "10", value: "Morning stiffness" },
  { id: "10", value: "Morning stiffness > 1 hour" },
  { id: "11", value: "Morning stiffness >1 hour" },
  { id: "118", value: "Menstruation stopped" },
  { id: "12", value: "Morning stiffness" },
  { id: "122", value: "Myalgia" },
  { id: "134", value: "Mucopurulent secretions" },
  { id: "135", value: "Myalgia" },
  { id: "14", value: "Myalgia" },
  { id: "141", value: "Myalgia" },
  { id: "18", value: "Melena" },
  { id: "18", value: "Myalgia" },
  { id: "19", value: "Myalgia" },
  { id: "2", value: "Melena" },
  { id: "27", value: "Myalgia" },
  { id: "28", value: "Myalgia" },
  { id: "29", value: "Myalgia" },
  { id: "3", value: "More severe if walk, breath, cough, or strain" },
  { id: "34", value: "Myalgia" },
  { id: "45", value: "Mucus from anus" },
  { id: "47", value: "Muscle weakness on the site of trauma" },
  { id: "48", value: "Muscle weakness on the site of trauma" },
  { id: "51", value: "Malaise" },
  { id: "51", value: "Milk-white urine" },
  { id: "52", value: "Mucosal edema" },
  { id: "58", value: "Myalgia" },
  { id: "70", value: "Multiple red dots on the body" },
  { id: "95", value: "Mouth Ulcer" },
  { id: "96", value: "Muscle stiffness" },
  { id: "96", value: "Muscle ache around wound" },
  { id: "102", value: "Nausea" },
  { id: "104", value: "Non vestibular Vertigo" },
  { id: "110", value: "Nausea" },
  { id: "111", value: "Nausea" },
  { id: "112", value: "Nausea and vomiting" },
  { id: "118", value: "Nausea" },
  { id: "120", value: "Nausea" },
  { id: "124", value: "Nasal congestion" },
  { id: "125", value: "Nasal congestion" },
  { id: "126", value: "Nasal congestion depends on position" },
  { id: "126", value: "Nasal congestion to a non-specific stimuli" },
  { id: "128", value: "Nausea" },
  { id: "13", value: "Night sweats" },
  { id: "131", value: "Nasal congestion" },
  { id: "134", value: "Nasal congestion" },
  { id: "134", value: "Nose pain" },
  { id: "136", value: "Nasal congestion" },
  { id: "14", value: "Nausea" },
  { id: "140", value: "Nausea" },
  { id: "142", value: "Nausea" },
  { id: "17", value: "Nausea" },
  { id: "18", value: "Nausea" },
  { id: "19", value: "Nausea" },
  { id: "22", value: "Nocturia" },
  { id: "22", value: "Nausea" },
  { id: "23", value: "Nausea" },
  { id: "24", value: "Nausea" },
  { id: "25", value: "No Appetite" },
  { id: "27", value: "Nausea" },
  { id: "28", value: "Nausea" },
  { id: "29", value: "Nausea" },
  { id: "3", value: "Nausea" },
  { id: "30", value: "Neck stiffness" },
  { id: "31", value: "Nausea" },
  { id: "33", value: "No complaint or symptoms" },
  { id: "36", value: "Nausea" },
  { id: "38", value: "Numbness at the extremities" },
  { id: "4", value: "Nausea" },
  { id: "43", value: "Not willing to suckle" },
  { id: "49", value: "Nausea" },
  { id: "5", value: "Nausea" },
  { id: "6", value: "Nausea" },
  { id: "79", value: "Neurological symptoms" },
  { id: "79", value: "Night bone pain" },
  { id: "81", value: "No symptoms" },
  { id: "87", value: "Nausea" },
  { id: "88", value: "Normal visual acuity" },
  { id: "95", value: "Night sweat" },
  { id: "96", value: "Neck stiffness" },
  { id: "99", value: "No consciousness between 2 seizures" },
  { id: "118", value: "Often urination" },
  { id: "122", value: "Odynophagia" },
  { id: "123", value: "Odynophagia" },
  { id: "131", value: "Odynophagia" },
  { id: "49", value: "Obstipation" },
  { id: "8", value: "Orthopnea" },
  { id: "100", value: "Posterior auricular pain" },
  { id: "102", value: "Pulsating headache" },
  { id: "102", value: "Photophobia" },
  { id: "102", value: "Pain on one side of head" },
  { id: "102", value: "Pain getting worse with physical activities" },
  { id: "103", value: "Palpitations" },
  { id: "105", value: "Pessimist" },
  { id: "105", value: "Palpitation" },
  { id: "109", value: "Psychomotor disorder" },
  { id: "110", value: "Pain sensation on the wound" },
  { id: "113", value: "Progressively increased blood pressure" },
  { id: "115", value: "Prolonge stage 1 or 2 labor" },
  { id: "117", value: "Pain" },
  { id: "119", value: "Pale" },
  { id: "121", value: "Pain on vagina" },
  { id: "123", value: "Pain may radiate to ear" },
  { id: "128", value: "Progressive in pain" },
  { id: "13", value: "Productive cough" },
  { id: "131", value: "Productive cough" },
  { id: "132", value: "Pain when chewing" },
  { id: "132", value: "Painful lump" },
  { id: "133", value: "Pain inside the nose" },
  {
    id: "134",
    value:
      "Patients or their parents talk that accidentally inserting object into the nasal cavity",
  },
  {
    id: "136",
    value: "Paroxysms coughs followed by a high-pitched “whoop” sound",
  },
  { id: "137", value: "Productive cough" },
  { id: "138", value: "Puffy face" },
  { id: "139", value: "Pale" },
  { id: "140", value: "Pale" },
  { id: "141", value: "Pruritic rash" },
  { id: "16", value: "Palpitation" },
  { id: "22", value: "Polacysuria" },
  { id: "26", value: "Productive cough" },
  { id: "27", value: "Photophobia" },
  { id: "28", value: "Pale-colored stool" },
  { id: "29", value: "Pruritic" },
  { id: "29", value: "Photophobia" },
  {
    id: "3",
    value: "Pain only on 1 site or spread over the abdominal region",
  },
  { id: "3", value: "Palpitate" },
  { id: "30", value: "Palpitation" },
  { id: "35", value: "Palpitation" },
  { id: "37", value: "Pale" },
  { id: "38", value: "Pruritus vulvae in woman" },
  { id: "38", value: "Polyuria (urinate a lot)" },
  { id: "38", value: "Polyphagia (eat a lot)" },
  { id: "38", value: "Polydipsia (drink a lot)" },
  {
    id: "39",
    value:
      "Patients come without complaints of overweight but with symptoms arising from health risks",
  },
  { id: "4", value: "Pain after eating fatty food" },
  { id: "4", value: "Pain ± 30-60 minutes without relief" },
  { id: "46", value: "Painless Lump under the skin" },
  { id: "47", value: "Pain on the site of trauma" },
  { id: "48", value: "Pain on the site of trauma" },
  { id: "5", value: "Pain on activity" },
  { id: "5", value: "Pain radiates to jaw" },
  { id: "5", value: "Pain radiates to left arm" },
  { id: "5", value: "Pain radiates to neck" },
  { id: "5", value: "Pain radiates to shoulder" },
  { id: "5", value: "Pale" },
  { id: "56", value: "Painful skin" },
  { id: "6", value: "Pain radiates to shoulder" },
  { id: "6", value: "Pain radiates to neck" },
  { id: "6", value: "Pain radiates to left arm" },
  { id: "6", value: "Pain radiates to jaw" },
  { id: "7", value: "Palpitation" },
  { id: "71", value: "Pain on skin" },
  { id: "72", value: "Palpitation" },
  { id: "73", value: "Pain on the skin" },
  { id: "74", value: "Painful on mouth" },
  { id: "75", value: "Painless" },
  { id: "76", value: "Pruritus nocturna" },
  { id: "76", value: "People surrounding has same issue" },
  { id: "77", value: "Painful sexual intercourse" },
  { id: "78", value: "Pain on genital" },
  { id: "79", value: "Place anywhere" },
  { id: "79", value: "Painless lesion" },
  { id: "8", value: "Paroxysmal nocturnal dyspnea" },
  { id: "80", value: "Pelvic pain" },
  { id: "80", value: "Post-coital bleeding" },
  { id: "81", value: "Pain on erection" },
  { id: "81", value: "Pus urination" },
  { id: "87", value: "Pain on the eyes" },
  { id: "89", value: "Pain" },
  { id: "9", value: "Palpitation" },
  { id: "90", value: "Pain" },
  { id: "91", value: "Pain on the eyelid" },
  { id: "91", value: "Photophobia" },
  { id: "103", value: "Radiating to neck and shoulder" },
  { id: "11", value: "Range of movement limitation" },
  { id: "11", value: "Red eyes" },
  { id: "12", value: "Range of movement limitation" },
  { id: "124", value: "Rhinorrhea" },
  { id: "125", value: "Rinorrhea" },
  { id: "127", value: "Reduce hearing" },
  { id: "128", value: "Reduce hearing" },
  { id: "130", value: "Reduce hearing" },
  { id: "133", value: "Rhinitis" },
  { id: "135", value: "Rhinorrhea" },
  {
    id: "144",
    value: "Rash spreading from head, face and all the body",
  },
  { id: "144", value: "Red eyes" },
  { id: "144", value: "Rhinorrhea" },
  { id: "145", value: "Rash" },
  { id: "16", value: "Reproduction system disorders" },
  { id: "18", value: "Retroorbital pain" },
  { id: "25", value: "Rapid Pulse" },
  { id: "4", value: "Radiating pain to right shoulder" },
  { id: "40", value: "Redness skin" },
  { id: "49", value: "Right lower quadrant pain" },
  { id: "52", value: "Rhinorrhea" },
  { id: "54", value: "Redish spotting" },
  { id: "55", value: "Recurrent" },
  { id: "56", value: "Reddish spotting" },
  { id: "59", value: "Radicular pain" },
  { id: "59", value: "Redness on skin" },
  { id: "60", value: "Redness on skin" },
  { id: "62", value: "Rough skin" },
  { id: "62", value: "Redness skin" },
  { id: "63", value: "Red patches" },
  { id: "64", value: "Redness around the mouth" },
  { id: "65", value: "Redness on the skin" },
  { id: "66", value: "Red spotting when sweating" },
  {
    id: "70",
    value: "Red dot pattern looks like an inverted pine tree",
  },
  { id: "71", value: "Redness on skin" },
  { id: "78", value: "Redness on genital" },
  { id: "79", value: "Redness on skin" },
  { id: "86", value: "Reading difficulty" },
  { id: "87", value: "Red eyes" },
  { id: "88", value: "Red eyes" },
  { id: "89", value: "Redness" },
  { id: "90", value: "Red eyes" },
  { id: "91", value: "Red eyes" },
  { id: "92", value: "Redness on the eyelid" },
  { id: "94", value: "Red spotting on the eye" },
  { id: "95", value: "Recurring infection" },
  { id: "10", value: "Shoulder pain" },
  { id: "10", value: "Shoulder stiffness" },
  { id: "100", value: "Sudden" },
  { id: "100", value: "Sensitive to sound" },
  { id: "103", value: "Shortness of breath" },
  { id: "105", value: "Sweating" },
  { id: "105", value: "Sleep disorder" },
  { id: "105", value: "Shortness of breath" },
  { id: "106", value: "Strange thought that does not real" },
  { id: "106", value: "Social withdrawal" },
  { id: "106", value: "Sleep Disorder" },
  { id: "106", value: "Scared " },
  { id: "108", value: "Seizure" },
  { id: "109", value: "Sleep cycle problem" },
  { id: "112", value: "Severe headache" },
  { id: "113", value: "Severe headache" },
  { id: "113", value: "Seizure" },
  { id: "116", value: "Shivering" },
  { id: "117", value: "Sometimes sepsis" },
  { id: "12", value: "Swollen joint" },
  { id: "120", value: "Shivering" },
  { id: "122", value: "Sore throat" },
  { id: "123", value: "Sore throat" },
  { id: "124", value: "Sneezing" },
  { id: "125", value: "Sneezing" },
  { id: "126", value: "Sneezing" },
  { id: "128", value: "Secretion" },
  { id: "13", value: "Sub febrile" },
  { id: "13", value: "Shortness of breath" },
  { id: "131", value: "Shortness of breath" },
  { id: "131", value: "Sneezing" },
  { id: "131", value: "Sore throat" },
  { id: "134", value: "Smell on one side of the nose" },
  { id: "135", value: "Sneezing" },
  { id: "135", value: "Sore throat" },
  { id: "136", value: "Subfebrile" },
  { id: "137", value: "Shortness of breath" },
  { id: "14", value: "Stomachache" },
  { id: "14", value: "Sweating" },
  { id: "15", value: "Shortness of breath" },
  { id: "17", value: "Seizure" },
  { id: "18", value: "Skin rash" },
  { id: "20", value: "Shortness of breath" },
  { id: "21", value: "Slymy stool" },
  { id: "22", value: "Supra pubic tenderness" },
  { id: "23", value: "Stomach burning sensation" },
  { id: "24", value: "Slymy stool" },
  { id: "24", value: "Soft stool" },
  { id: "24", value: "Stomacache" },
  { id: "25", value: "Sweating" },
  { id: "25", value: "Swollen lymph nodes and pain when touched" },
  { id: "26", value: "Shortness of breath" },
  { id: "29", value: "Sub febrile" },
  { id: "3", value: "Shortness of breath" },
  { id: "32", value: "Steatorrhea" },
  { id: "34", value: "Sudden arthralgia" },
  { id: "35", value: "Seizure" },
  { id: "38", value: "Slow wound healing" },
  { id: "40", value: "Shortness of breath" },
  { id: "44", value: "Skin Pain" },
  { id: "47", value: "Swelling on the site of trauma" },
  { id: "47", value: "Skin discoloration on the site of trauma" },
  { id: "47", value: "Sensibility impairment on the site of trauma" },
  { id: "48", value: "Sensibility impairment on the site of trauma" },
  { id: "48", value: "Skin discoloration on the site of trauma" },
  { id: "48", value: "Swelling on the site of trauma" },
  { id: "5", value: "Shortness of breath" },
  { id: "51", value: "Swollen lymph nodes" },
  { id: "52", value: "Shortness of breath" },
  { id: "56", value: "Sore" },
  { id: "6", value: "Shortness of breath" },
  { id: "60", value: "Small lump on the skin" },
  { id: "62", value: "Smelly" },
  { id: "63", value: "Scaly" },
  { id: "64", value: "Subfebris" },
  { id: "65", value: "Subfebris" },
  { id: "67", value: "Skin redness" },
  { id: "7", value: "Sweating" },
  { id: "7", value: "Shortness of breath" },
  { id: "70", value: "Single bigger red spot" },
  { id: "71", value: "Swelling in the area of the bitten body" },
  { id: "72", value: "Shortness of breath" },
  { id: "73", value: "Scab" },
  { id: "74", value: "Sense of metal" },
  { id: "75", value: "Skin patch" },
  { id: "77", value: "Smell on genital" },
  { id: "82", value: "Short distance reading" },
  { id: "84", value: "Sore eyes" },
  { id: "87", value: "Sudden Loss of visual acuity" },
  { id: "88", value: "Secret on the eyes" },
  { id: "9", value: "Shortness of breath" },
  { id: "9", value: "Syncope" },
  { id: "90", value: "Swelling eyelid" },
  { id: "90", value: "Spraging" },
  { id: "92", value: "Spraged on the eyelid" },
  { id: "95", value: "Skin rash" },
  { id: "95", value: "Sore throat" },
  { id: "96", value: "Spasm" },
  { id: "96", value: "Seizure" },
  { id: "97", value: "Sudden blindness" },
  { id: "97", value: "Sensory disorder on one side of body" },
  { id: "97", value: "Seizure" },
  { id: "98", value: "Seizure" },
  { id: "99", value: "Seizure  more than 30 minutes" },
  { id: "100", value: "Tingling" },
  { id: "106", value: "Talk disorderly" },
  { id: "110", value: "Tingling sensation on the wound" },
  { id: "111", value: "Thirsty" },
  { id: "119", value: "Tinnitus" },
  { id: "127", value: "Tinnitus" },
  { id: "130", value: "Tinnitus" },
  { id: "131", value: "Thick mucus" },
  { id: "138", value: "Thin hair, redness and easily fall" },
  { id: "15", value: "Tachypnea" },
  { id: "16", value: "Tremor" },
  { id: "24", value: "Tenesmus" },
  { id: "27", value: "Thigh tenderness" },
  { id: "31", value: "Throat itching" },
  { id: "35", value: "Trembling" },
  { id: "75", value: "Tingling sensation" },
  { id: "100", value: "Upper and lower face’s muscle paralysis" },
  { id: "127", value: "Unilateral" },
  { id: "137", value: "Uncomfortable chest" },
  { id: "141", value: "Urticaria" },
  { id: "22", value: "Urine with blood" },
  { id: "4", value: "Upper right quadrant abdominal pain" },
  { id: "41", value: "Unconscious" },
  { id: "52", value: "Urticaria" },
  { id: "7", value: "Uncomfortable in chest" },
  { id: "79", value: "Uncomfortable feeling" },
  { id: "90", value: "Uncomfortable on eyes" },
  { id: "102", value: "Vomiting" },
  { id: "104", value: "Vestibular Vertigo" },
  { id: "111", value: "Vomiting" },
  { id: "113", value: "Vomiting" },
  { id: "117", value: "Vaginal bleeding" },
  {
    id: "117",
    value: "Vaginal bleeding after a delay of hours to days",
  },
  { id: "118", value: "Vomit in the morning" },
  { id: "120", value: "Vomiting" },
  { id: "121", value: "Vaginal bleeding" },
  { id: "128", value: "Vomiting" },
  { id: "130", value: "Vertigo" },
  { id: "131", value: "Voice lost" },
  { id: "136", value: "Vomit during or after cough" },
  { id: "138", value: "Very thin" },
  { id: "14", value: "Vomiting" },
  { id: "140", value: "Vomit" },
  { id: "142", value: "Vomit" },
  { id: "17", value: "Visual disturbance" },
  { id: "17", value: "Vomiting" },
  { id: "18", value: "Vomiting" },
  { id: "19", value: "Vomiting" },
  { id: "21", value: "Vomiting" },
  { id: "22", value: "Vomiting" },
  { id: "23", value: "Vomiting" },
  { id: "24", value: "Vomiting" },
  { id: "27", value: "Vomiting" },
  { id: "28", value: "Vomiting" },
  { id: "29", value: "Vomiting" },
  { id: "3", value: "Vomiting" },
  { id: "31", value: "Vomiting" },
  { id: "36", value: "Vomiting" },
  { id: "38", value: "Vision disturbance" },
  { id: "49", value: "Vomiting" },
  { id: "5", value: "Vomiting" },
  { id: "52", value: "Vomit" },
  { id: "53", value: "Very itchy on skin" },
  { id: "58", value: "Vesicles on perioral" },
  { id: "58", value: "Vulvovaginitis in female" },
  { id: "59", value: "Vesicle in group" },
  { id: "6", value: "Vomiting" },
  { id: "72", value: "Vomiting" },
  { id: "77", value: "Vaginal discharge" },
  { id: "80", value: "Vaginal discharge" },
  { id: "86", value: "Visual decreasing slowly" },
  { id: "87", value: "Vomiting" },
  { id: "93", value: "Vision decreases at night" },
  { id: "97", value: "Vertigo" },
  { id: "111", value: "Weight loss" },
  { id: "116", value: "Weakness" },
  { id: "122", value: "Weakness" },
  { id: "124", value: "Watery eyes" },
  { id: "13", value: "Weight loss" },
  { id: "135", value: "Weakness" },
  { id: "136", value: "Watery eyes" },
  { id: "136", value: "Weakness" },
  { id: "138", value: "Wrinkle skin" },
  { id: "138", value: "Whinny" },
  { id: "140", value: "Worm in stool" },
  { id: "140", value: "Weight loss" },
  { id: "143", value: "Weight loss" },
  { id: "16", value: "Weight loss" },
  { id: "17", value: "Weakness" },
  { id: "2", value: "Weight loss" },
  { id: "20", value: "Wheezing" },
  { id: "21", value: "Watery stool" },
  { id: "22", value: "Waist Pain" },
  { id: "24", value: "Watery stool" },
  { id: "25", value: "Weakness" },
  { id: "27", value: "Waist tenderness" },
  { id: "28", value: "Weakness" },
  { id: "37", value: "Weakness" },
  { id: "38", value: "Weak" },
  { id: "41", value: "Weakness" },
  { id: "45", value: "Weakness" },
  { id: "50", value: "Wet and become wound" },
  { id: "51", value: "Warm and painful lymph node" },
  { id: "52", value: "Wheezing" },
  { id: "55", value: "Wet red spots skin lesion" },
  { id: "61", value: "Warts on the skin or mucosa" },
  { id: "69", value: "White patches on skin" },
  { id: "74", value: "White patch inside the mouth" },
  { id: "84", value: "Watery eyes" },
  { id: "88", value: "Watery eyes" },
  { id: "91", value: "Watery eye" },
  { id: "95", value: "Weight loss" },
  { id: "97", value: "Weakness on one side of body" },
  { id: "98", value: "Wetting after seizure" },
  { id: "81", value: "Yellowish pus" },
];

const educations = {
  options: {
    not_finished_elementary: {
      value: "not_finished_elementary",
    },
    elementary_school_graduate: {
      value: "elementary_school_graduate",
    },
    junior_high_school_graduate: {
      value: "junior_high_school_graduate",
    },
    senior_high_school_graduate: {
      value: "senior_high_school_graduate",
    },
    university_graduate: {
      value: "university_graduate",
    },
    no_formal_education: {
      value: "no_formal_education",
    },
  },
};

const occupation = {
  options: {
    farmer: {
      value: "farmer",
    },
    fisherman: {
      value: "fisherman",
    },
    merchants: {
      value: "merchants",
    },
    public_officer: {
      value: "public_officer",
    },
    police_officer: {
      value: "police_officer",
    },
    army: {
      value: "army",
    },
    private_officer: {
      value: "private_officer",
    },
    entrepreneur: {
      value: "entrepreneur",
    },
    retirement: {
      value: "retirement",
    },
    freelance_worker: {
      value: "freelance_worker",
    },
    unemployment: {
      value: "unemployment",
    },
    others: {
      value: "others",
    },
  },
};

export const getComplaintOptions = () => {
  return [
    "Voice lost",
    "Reduce hearing",
    "Smelly",
    "Vomiting",
    "Fever",
    "Ear pain",
  ];
};

export const LOCATIONS = [
  ["3", "WATES"],
  ["4", "SENTOLO 2"],
  ["5", "KALIBAWANG"],
  ["6", "PENGASIH 1"],
  ["7", "LENDAH 2"],
  ["8", "SENTOLO 1"],
  ["9", "PANJATAN 1"],
  ["10", "TEMON 1"],
  ["11", "KOKAP 1"],
  ["12", "LENDAH 1"],
  ["13", "SAMIGALUH 1"],
  ["14", "SAMIGALUH 2"],
  ["15", "GIRIMULYO 1"],
  ["16", "GIRIMULYO 2"],
  ["17", "NANGGULAN"],
  ["18", "KOKAP 2"],
  ["19", "PENGASIH 2"],
  ["20", "TEMON 2"],
  ["21", "PANJATAN 2"],
  ["22", "GALUR 1"],
  ["23", "GALUR 2"],
];

const insurance = {
  options: {
    bpjs: { value: "bpjs" },
    not_using_insurance: { value: "not_using_insurance" },
    others: { value: "others" },
  },
};

const getOptions =
  (options: AnyObject) => (): { id: string; name: string }[] => {
    return Object.keys(options).map((name) => ({
      id: name,
      name: name.split("_").join(" "),
    }));
  };

export const getEducationOptions = getOptions(educations.options);
export const getOccupationOptions = getOptions(occupation.options);
export const getInsuranceOptions = getOptions(insurance.options);
